name: fiji-automator
channels:
  - conda-forge
  - defaults
dependencies:
  # Python and core packages
  - python=3.9
  - pip
  
  # Scientific computing
  - numpy>=1.21.0
  - scipy
  
  # Image processing
  - pillow>=8.3.0
  - imageio
  - scikit-image
  
  # Data analysis
  - pandas>=1.3.0
  - matplotlib
  - seaborn
  
  # File I/O and utilities
  - tqdm
  - psutil>=5.8.0
  
  # Development and testing
  - pytest
  - pytest-cov
  - black
  - flake8
  
  # Jupyter for analysis
  - jupyter
  - ipykernel
  
  # Optional packages via pip
  - pip:
    # Additional packages not available in conda
    - tifffile>=2021.7.2
    - nd2reader  # For Nikon files
    - czifile    # For Zeiss files
    - bioformats # For various microscopy formats (requires Java)
    
    # Development tools
    - mypy
    - pre-commit
    
    # Documentation
    - sphinx
    - sphinx-rtd-theme 